In [1]:
import numpy as np
import pandas as pd
import cv2
from matplotlib import pyplot as plt
import os



In [23]:
#x = np.array([2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2.0, 1.0, 1.5, 1.1])
#y = np.array([2.4, 0.7, 2.9, 2.2, 3.0, 2.7, 1.6, 1.1, 1.6, 0.9])

x = np.array([1, 1, -1, -1])
y = np.array([1, -1, 1, -1])
z = np.array([3, 3, 3, 3])
df= pd.DataFrame({'X': x, 'Y': y, 'Z': z})



In [24]:
x = np.mean(x)
x

0.0

In [25]:
y = np.mean(y)
y

0.0

In [26]:
z = np.mean(z)
z

3.0

In [27]:
df_mean = df - df.mean(axis=0)
df_mean

X    Y    Z
0  1.0  1.0  0.0
1  1.0 -1.0  0.0
2 -1.0  1.0  0.0
3 -1.0 -1.0  0.0

In [28]:
df_cov = df_mean.cov()
df_cov

X         Y    Z
X  1.333333  0.000000  0.0
Y  0.000000  1.333333  0.0
Z  0.000000  0.000000  0.0

In [29]:
eigenval, eigenvect = np.linalg.eig(df_cov)
eigenval

array([1.33333333, 1.33333333, 0.        ])

In [30]:
 eigenvect

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
eigval_sort_idx = np.argsort(eigenval)
eigval_sort_idx

array([2, 0, 1])

In [76]:
feature_vector = eigenvect[:, eigval_sort_idx[1:]]
feature_vector

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [77]:
#row_feature_vector = feature_vector.T
row_feature_vector = np.array([[0], [1],[1]])
row_feature_vector = row_feature_vector.T
row_data_adjust = df_mean.T

df_reduced = np.matmul(row_feature_vector, row_data_adjust)

df_reduced

array([[ 1., -1.,  1., -1.]])

In [78]:
#get the row data
row_data_adjust = np.matmul(row_feature_vector.T, df_reduced)
row_data_adjust

array([[ 0.,  0.,  0.,  0.],
       [ 1., -1.,  1., -1.],
       [ 1., -1.,  1., -1.]])

In [79]:
#revert to dataframe
row_data_adjust_df = pd.DataFrame(row_data_adjust.T, columns=['X', 'Y', 'Z'])
row_data_adjust_df

X    Y    Z
0  0.0  1.0  1.0
1  0.0 -1.0 -1.0
2  0.0  1.0  1.0
3  0.0 -1.0 -1.0

In [80]:
df_mean

X    Y    Z
0  1.0  1.0  0.0
1  1.0 -1.0  0.0
2 -1.0  1.0  0.0
3 -1.0 -1.0  0.0

In [81]:
#add the mean to each column
original_data = row_data_adjust_df + df_mean
original_data

X    Y    Z
0  1.0  2.0  1.0
1  1.0 -2.0 -1.0
2 -1.0  2.0  1.0
3 -1.0 -2.0 -1.0

In [82]:
#cosmetic fix
original_data =original_data.round()

original_data

X    Y    Z
0  1.0  2.0  1.0
1  1.0 -2.0 -1.0
2 -1.0  2.0  1.0
3 -1.0 -2.0 -1.0

In [74]:
df.head()

X  Y  Z
0  1  1  3
1  1 -1  3
2 -1  1  3
3 -1 -1  3